include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - ios/**
    - web/**
    - lib/core/proto/**
    - lib/l10n/app_localizations*.dart

linter:
  rules:
    avoid_print: true
    use_build_context_synchronously: true
